name: firstwork
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: start
        run: echo "started now"
      - name: finished
        run: echo 'it is finishedDDDDD'
  second_job:
    needs: first_job
    runs-on: windows-latest
    steps:
      - name: kir-
        run: echo "kir-1"

      - name: kir-2
        run: echo "kir-2"
